### ISSUE TITLE
consistent language for all labels

### ISSUE THREAD

**Issue by MichaelKreil** [versatiles-org/shortbread-tilemaker#1]
e.g.:
1. all English
2. all German
3. all local language

**Comment by yetzt** [comment]
since the `boundary_labels` are static, i've extended the data thus:

* `name` is a single localized name ("Schweiz")
* `name_full` is the complete localized name (including alternatives in different languages, "Schweiz / Suisse / Svizzera / Svizra")
* `name_latin` is a latin representation of the name, if `name` is not latin ("Қазақстан" → "Kazakhstan"; not in process.lua yet)
* `name_de` and `name_en` remain as they are in shortbread. 

maybe this logic can be applied to other place names as well, though osm is inconsistant in this regard
